server:
  port: 2060

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/827Project
    #url: jdbc:postgresql://211.253.9.11:5432/goldspoondb
    username: postgres
    password: search2021!@

  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    properties:
      hibernate:
        show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    generate-ddl: true

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method