server:
  port: 2060

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/827Project
    #url: jdbc:postgresql://211.253.9.11:5432/goldspoondb
    username: admin
    password: ai1234!

  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    properties:
      hibernate:
        show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method